# Generated by Django 3.1.2 on 2020-10-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_description', models.CharField(max_length=20)),
                ('price_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('renter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=300)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.IntegerField()),
                ('electric_meter', models.IntegerField()),
                ('water_meter', models.IntegerField()),
                ('room_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True)),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.renter')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
