# Generated by Django 3.1.2 on 2020-11-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
