# Generated by Django 3.1.2 on 2020-10-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_description',
            field=models.CharField(max_length=30),
        ),
    ]
