# Generated by Django 3.1.2 on 2020-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201031_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
