# Generated by Django 3.1.2 on 2020-10-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicecharge_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promblem_description', models.TextField(max_length=100)),
                ('problem_date', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.FloatField()),
                ('payment_date', models.DateField()),
                ('sc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecharge')),
            ],
        ),
    ]
