# Generated by Django 3.1.2 on 2020-11-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201101_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
