# Generated by Django 3.1.2 on 2020-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_servicecharge_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='add_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
