# Generated by Django 3.1.2 on 2020-11-02 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201102_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='add_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='payment_status',
            field=models.IntegerField(default=1),
        ),
    ]
