# Generated by Django 3.1.2 on 2020-11-02 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201102_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='add_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
