# Generated by Django 3.1.2 on 2020-11-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201102_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='payment_status',
            field=models.IntegerField(default=1),
        ),
    ]
