# Generated by Django 3.1.2 on 2020-11-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201102_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.IntegerField(default=1),
        ),
    ]
